const PDFDocument = require('pdfkit');
const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

class ReportGenerationService {
  async generatePDF(data, options = {}) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50
        });

        const chunks = [];
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // Header
        doc.fontSize(20)
          .text('EMPS Report', { align: 'center' })
          .moveDown();

        // Title
        doc.fontSize(16)
          .text(options.title || 'System Report', { align: 'center' })
          .moveDown();

        // Date
        doc.fontSize(10)
          .text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' })
          .moveDown();

        // Summary
        doc.fontSize(12)
          .text('Summary', { underline: true })
          .moveDown(0.5);

        if (data.summary) {
          doc.text(data.summary);
          doc.moveDown();
        }

        // Metrics
        if (data.metrics) {
          doc.fontSize(12)
            .text('Metrics', { underline: true })
            .moveDown(0.5);

          const metrics = data.metrics;
          const items = [
            ['Total Employees', metrics.totalEmployees || 0],
            ['Present Today', metrics.presentEmployees || 0],
            ['Tasks Completed', metrics.tasksCompleted || 0],
            ['Productivity', metrics.productivity || 'N/A']
          ];

          items.forEach(([label, value]) => {
            doc.fontSize(10)
              .text(`${label}: ${value}`, { indent: 20 });
          });
          doc.moveDown();
        }

        // Data Table
        if (data.tableData && data.tableData.length > 0) {
          doc.fontSize(12)
            .text('Details', { underline: true })
            .moveDown(0.5);

          const tableData = data.tableData.slice(0, 20);
          const headers = Object.keys(tableData[0] || {});
          const columnWidth = 80;

          headers.forEach((header, i) => {
            doc.fontSize(8)
              .text(header, 50 + i * columnWidth, doc.y, {
                width: columnWidth - 5,
                align: 'left'
              });
          });

          doc.moveDown();

          tableData.forEach(row => {
            headers.forEach((header, i) => {
              doc.fontSize(8)
                .text(String(row[header] || ''), 50 + i * columnWidth, doc.y, {
                  width: columnWidth - 5,
                  align: 'left'
                });
            });
            doc.moveDown();
          });
        }

        // Footer
        doc.fontSize(8)
          .text('Generated by EMPS', 50, doc.page.height - 50, {
            align: 'center'
          });

        doc.end();

      } catch (error) {
        reject(error);
      }
    });
  }

  async generateExcel(data) {
    try {
      const workbook = XLSX.utils.book_new();

      // Summary sheet
      const summaryData = [
        ['Summary Report'],
        ['Generated:', new Date().toLocaleString()],
        []
      ];

      if (data.summary) {
        summaryData.push(['Summary', data.summary]);
      }

      if (data.metrics) {
        summaryData.push([]);
        summaryData.push(['Metrics', 'Value']);
        for (const [key, value] of Object.entries(data.metrics)) {
          summaryData.push([key, value]);
        }
      }

      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

      // Data sheet
      if (data.tableData && data.tableData.length > 0) {
        const headers = Object.keys(data.tableData[0] || {});
        const rows = [headers];
        
        data.tableData.forEach(item => {
          const row = headers.map(header => item[header] || '');
          rows.push(row);
        });

        const dataSheet = XLSX.utils.aoa_to_sheet(rows);
        XLSX.utils.book_append_sheet(workbook, dataSheet, 'Data');
      }

      // Additional data
      if (data.additionalSheets) {
        for (const [name, sheetData] of Object.entries(data.additionalSheets)) {
          const sheet = XLSX.utils.json_to_sheet(sheetData);
          XLSX.utils.book_append_sheet(workbook, sheet, name);
        }
      }

      const buffer = XLSX.write(workbook, { 
        type: 'buffer', 
        bookType: 'xlsx' 
      });

      return buffer;
    } catch (error) {
      console.error('Excel generation error:', error);
      throw error;
    }
  }

  async generateCSV(data) {
    try {
      if (!data.tableData || data.tableData.length === 0) {
        return Buffer.from('');
      }

      const headers = Object.keys(data.tableData[0] || {});
      let csv = headers.join(',') + '\n';

      data.tableData.forEach(item => {
        const row = headers.map(header => {
          const value = item[header] || '';
          return `"${String(value).replace(/"/g, '""')}"`;
        });
        csv += row.join(',') + '\n';
      });

      return Buffer.from(csv);
    } catch (error) {
      console.error('CSV generation error:', error);
      throw error;
    }
  }

  async generateAttendanceReport(attendanceData) {
    const data = {
      summary: `Attendance Report for ${attendanceData.period || 'Current Period'}`,
      metrics: {
        totalEmployees: attendanceData.totalEmployees,
        presentEmployees: attendanceData.presentEmployees,
        absentEmployees: attendanceData.absentEmployees,
        attendanceRate: attendanceData.attendanceRate + '%',
        totalWorkingHours: attendanceData.totalWorkingHours || 0,
        totalOvertime: attendanceData.totalOvertime || 0
      },
      tableData: attendanceData.employees || []
    };

    return data;
  }

  async generateTaskReport(taskData) {
    const data = {
      summary: `Task Report for ${taskData.period || 'Current Period'}`,
      metrics: {
        totalTasks: taskData.totalTasks,
        completedTasks: taskData.completedTasks,
        pendingTasks: taskData.pendingTasks,
        inProgressTasks: taskData.inProgressTasks,
        overdueTasks: taskData.overdueTasks,
        completionRate: taskData.completionRate + '%'
      },
      tableData: taskData.tasks || [],
      additionalSheets: {
        'By Priority': taskData.byPriority || [],
        'By Department': taskData.byDepartment || []
      }
    };

    return data;
  }

  async generateLeaveReport(leaveData) {
    const data = {
      summary: `Leave Report for ${leaveData.period || 'Current Period'}`,
      metrics: {
        totalLeaves: leaveData.totalLeaves,
        approvedLeaves: leaveData.approvedLeaves,
        pendingLeaves: leaveData.pendingLeaves,
        rejectedLeaves: leaveData.rejectedLeaves,
        totalDays: leaveData.totalDays || 0
      },
      tableData: leaveData.leaves || [],
      additionalSheets: {
        'By Type': leaveData.byType || [],
        'By Department': leaveData.byDepartment || []
      }
    };

    return data;
  }

  async generatePerformanceReport(performanceData) {
    const data = {
      summary: `Performance Report for ${performanceData.period || 'Current Period'}`,
      metrics: {
        averageProductivity: performanceData.averageProductivity + '%',
        topPerformers: performanceData.topPerformers?.length || 0,
        totalEmployees: performanceData.totalEmployees || 0
      },
      tableData: performanceData.employees || [],
      additionalSheets: {
        'Top Performers': performanceData.topPerformers || []
      }
    };

    return data;
  }
}

module.exports = new ReportGenerationService();