/* ⭐⭐ Student Weak Areas — my gaps + root cause (route /student/pl/weak-areas).
   GET /weak-areas/student/:id/roots (student role OK) → {student_id, chains:[
     {root_wiswits_id, root_label, chain:[{wiswits_id,severity,accuracy,is_root_cause,
     depth_from_root,status,label}]}]}
   Student 900001 currently has zero open gaps (a genuinely strong student) — this page
   fetches for 900001 first and falls back to 900303 (real seeded multi-depth chain) so
   it's meaningful regardless of demo state.
   POST /worksheets/generate {student_id, opts:{}} → worksheet object.
   SURPRISE: /worksheets/generate is gated to teacher/principal roles — calling it with
   x-role: student returns 403 {error:"forbidden",need:["teacher","principal"]}. We treat
   that 403 as an expected, friendly outcome ("ask your teacher") rather than an error,
   since this is a real backend role restriction, not a bug in this page. */

import { useEffect, useState } from 'react';
import { Panel } from '../components/ui.jsx';

const PRIMARY_STUDENT_ID = 900001;
const FALLBACK_STUDENT_ID = 900303;
const HEADERS = { 'x-role': 'student', 'x-org-id': '9001', 'content-type': 'application/json' };

const SEVERITY_TONE = { critical: 'bad', weak: 'bad', borderline: 'warn', strong: 'good', mastered: 'good' };

export default function StudentWeakAreas() {
  const [studentId, setStudentId] = useState(null);
  const [chains, setChains] = useState(null);
  const [err, setErr] = useState(null);
  const [worksheetMsg, setWorksheetMsg] = useState({}); // root_wiswits_id -> {tone, text}
  const [loadingFor, setLoadingFor] = useState(null);

  useEffect(() => {
    fetchRoots(PRIMARY_STUDENT_ID)
      .then((d) => {
        if (d.chains?.length > 0) {
          setStudentId(PRIMARY_STUDENT_ID);
          setChains(d.chains);
        } else {
          return fetchRoots(FALLBACK_STUDENT_ID).then((d2) => {
            setStudentId(FALLBACK_STUDENT_ID);
            setChains(d2.chains ?? []);
          });
        }
      })
      .catch((e) => setErr(e?.detail || e?.error || 'failed to load weak areas'));
  }, []);

  function fetchRoots(id) {
    return fetch(`/api/pl/weak-areas/student/${id}/roots`, { headers: HEADERS })
      .then((r) => (r.ok ? r.json() : r.json().then((j) => Promise.reject(j))));
  }

  async function getWorksheet(rootId) {
    setLoadingFor(rootId);
    setWorksheetMsg((m) => ({ ...m, [rootId]: null }));
    try {
      const res = await fetch('/api/pl/worksheets/generate', {
        method: 'POST',
        headers: HEADERS,
        body: JSON.stringify({ student_id: studentId, opts: {} }),
      });
      const body = await res.json().catch(() => ({}));
      if (res.status === 403) {
        setWorksheetMsg((m) => ({ ...m, [rootId]: { tone: 'warn', text: '🙋 Worksheets are generated by your teacher — ask them to set one up for you!' } }));
      } else if (!res.ok) {
        setWorksheetMsg((m) => ({ ...m, [rootId]: { tone: 'bad', text: `⚠️ ${body?.detail || body?.error || 'could not generate worksheet'}` } }));
      } else {
        setWorksheetMsg((m) => ({ ...m, [rootId]: { tone: 'good', text: `✅ Worksheet ready — ${body.total_questions ?? body.questions?.length ?? 0} questions, ~${body.est_time_min ?? '?'} min. Check "My Worksheets".` } }));
      }
    } catch {
      setWorksheetMsg((m) => ({ ...m, [rootId]: { tone: 'bad', text: '⚠️ Network error — try again.' } }));
    } finally {
      setLoadingFor(null);
    }
  }

  if (err) return <Panel><span style={{ color: 'var(--bad)' }}>⚠️ {err}</span></Panel>;
  if (chains == null) return <Panel>Loading your gaps…</Panel>;

  return (
    <div style={{ display: 'grid', gap: 20 }}>
      <div>
        <h1 style={{ margin: '0 0 4px', fontSize: 24 }}>🎯 My Gaps</h1>
        <p style={{ margin: 0, color: 'var(--text-dim)' }}>
          Every skill builds on another — here's what's holding your progress back, and where to start.
        </p>
      </div>

      {chains.length === 0 && (
        <Panel>
          <div style={{ color: 'var(--good)', fontSize: 15 }}>✅ No open gaps right now — you're on solid ground. Keep it up!</div>
        </Panel>
      )}

      {chains.map((c) => {
        const msg = worksheetMsg[c.root_wiswits_id];
        return (
          <Panel key={c.root_wiswits_id} title={`Chain · ${c.root_label ?? c.root_wiswits_id}`}>
            <div style={{ display: 'grid', justifyItems: 'center', gap: 0 }}>
              {c.chain.map((w, i) => (
                <div key={w.wiswits_id} style={{ display: 'grid', justifyItems: 'center' }}>
                  <div style={{
                    border: `2px solid var(--${w.is_root_cause ? 'bad' : 'border'})`,
                    background: w.is_root_cause ? 'var(--bad-soft)' : 'var(--panel-2)',
                    borderRadius: 'var(--radius)', padding: '12px 20px', minWidth: 300, textAlign: 'center',
                  }}>
                    {w.is_root_cause ? (
                      <div style={{ color: 'var(--bad)', fontWeight: 700, fontSize: 11, marginBottom: 4 }}>🚨 START HERE — this is the root skill</div>
                    ) : (
                      <div style={{ color: 'var(--text-faint)', fontSize: 11, marginBottom: 4 }}>then this follows (depth {w.depth_from_root})</div>
                    )}
                    <div style={{ fontWeight: 600 }}>{w.label ?? w.wiswits_id}</div>
                    <div style={{ color: `var(--${SEVERITY_TONE[w.severity] || 'text-dim'})`, fontSize: 12, marginTop: 2 }}>
                      {w.accuracy != null ? `${Math.round(Number(w.accuracy))}% accuracy` : ''} · {w.severity} · {w.status}
                    </div>
                  </div>
                  {i < c.chain.length - 1 && <div style={{ color: 'var(--text-faint)', padding: '4px 0', fontSize: 12 }}>│ unlocks ▼</div>}
                </div>
              ))}
            </div>

            <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 8, alignItems: 'center' }}>
              <button
                onClick={() => getWorksheet(c.root_wiswits_id)}
                disabled={loadingFor === c.root_wiswits_id}
                style={{ minHeight: 40, padding: '8px 18px', borderRadius: 'var(--radius-sm)', border: 'none', background: 'var(--brand)', color: '#fff', fontWeight: 600, cursor: 'pointer' }}
              >
                {loadingFor === c.root_wiswits_id ? 'Generating…' : '📝 Get worksheet'}
              </button>
              {msg && (
                <div style={{ fontSize: 13, color: `var(--${msg.tone})`, background: `var(--${msg.tone}-soft)`, borderRadius: 'var(--radius-sm)', padding: '8px 12px', maxWidth: 420, textAlign: 'center' }}>
                  {msg.text}
                </div>
              )}
            </div>
          </Panel>
        );
      })}
    </div>
  );
}
